window.chillActionVeriteData = {
    action: [
        "Fais une danse avec {joueur2}.",
        "Fais un cri de singe.",
        "Saute à cloche pied pendant 1 minute.",
        "Fais une roulade avant.",
        "Fais un calin à {joueur2}.",
        "Fais 3 saut pied jouin.", 
        "Fais des bruits de bouche jusqu'au prochain tour.",
        "Cours pendant 1 minute.", 
        "Fais un bruit de prout.",
        "Fais semblant d'avoir mal quelque part jusqu'a ton prochain gage.",  
        "Imite un bébé jusqu'a ton prochain gage.", 
        "Imite pendant 15 secondes {joueur2}.", 
        "Regarde dans les yeux {joueur2} jusqu'au prochain tour.", 
        "Fais une déclaration d'amour à {joueur2}.",
        "Fais semblant d'être un animal jusqu'au prochain tour.",
        "Chante une chanson avec de l'eau dans ta bouche pendant 30 secondes.",
        "Active une alarme à 7 heures du matin sur ton téléphone.",
        "Porte une tenue choisie par {joueur2} jusqu'au prochain tour.",
        "Échange tes chaussettes avec {joueur2} jusqu'au prochain tour.",
        "Fais un compliment sincère à {joueur2}.",
        "Fais une danse ridicule pendant 30 secondes.",
        "Chatouille {joueur2} pendant 15 secondes.",
        "Lèche ton coude.",
        "Mets une note insta qui n'a aucun sens.",
        "Fais un spectacle de marionnettes avec tes chaussettes.",
        "Cite une chose que tout le monde aime, mais que toi tu n'aimes pas.",
        "Tu dois donner ton téléphone à {joueur2}, qui va le garder pendant 5 tours.",
        "Tourne 10 fois sur toi-même, puis fais la bise à {joueur2}.",
        "Fais un bras de fer avec le joueur de ton choix.",
        "Finis toutes tes phrases par 'ça ne fait aucun doute' jusqu'a ton prochain tour.",
        "Jusqu'à ton prochain tour, parles avec un accent marseillais.",
        "Jusqu'à ton prochain tour, parles avec un accent de gitan.",
        /* 32 */
    ],
    truth: [
        "Quelle est la chose la plus embarrassante que tu aies déjà faite ?",
        "Si tu étais professeur, quelle serait la matière que tu aimerais enseigner ?",
        "Quelle est la chose la plus bizarre que tu aies mangé ?",
        "Combien de jours as-tu passé sans te laver ?",
        "Dans combien de pays as-tu voyagé ?",
        "Quel était ton surnom quand tu étais petit(e) ?",
        "Quelle est ta plus grande honte ?",
        "Est-ce que tu as déjà menti pour que quelqu’un t’apprécie ?",
        "De quoi as-tu le plus peur ?",
        "As-tu déjà triché à un examen ?",
        /* 10 */
    ]
};
